const DECREASE = 'DECREASE';
const INCREASE = 'INCREASE';
const CLEAR_CART = 'CLEAR_CART';
const REMOVE = 'REMOVE';
const GET_TOTALS = 'GET_TOTALS';

export { DECREASE, INCREASE, CLEAR_CART, REMOVE, GET_TOTALS };
